image:
  repository: 783633885093.dkr.ecr.us-west-2.amazonaws.com/refractr
  tag: v0.0.7-4-gb1ff42b

imagePullSecrets:
  - name: ecr-registry

my_issuer:
  create: false

deployment:
  extraContainers:
  - name: syslog
    image: busybox
    command: ['nc', '-l', '-u', '127.0.0.1', '5114']
    ports:
      - name: syslog
        containerPort: 5114

cert-manager:
  install: true
  installCRDs: true

nginx-ingress:
  controller:
    service:
      type: ClusterIP
