language: minimal
sudo: required
if: branch = main
stages:
- Lint and Validate
- Deploy
install:
- "./ci/setup.sh"
jobs:
- stage: Lint and Validate
  script:
  - "./ci/lint.sh"
- stage: e2e
  script:
  - "./ci/e2e.sh"
- stage: Deploy
  if: type = push AND branch = main
  script:
  - "./ci/release.sh"
  deploy:
    provider: pages
    github_token: "$GITHUB_TOKEN"
    local_dir: releases
    verbose: true
    keep_history: true
    skip_cleanup: true
    target_branch: gh-pages
    on:
      branch: main
git:
  depth: false
env:
  global:
  - secure: JMQG7Yl/OqA0SRO7bYsZjP1d/VQ1IVutZ+7USKFIcSIWl7Qi9pnHnBTJVfs2Wa3rYcjHRSfd+oSjc9OKHY0QwQ8vPYURWeaDGYLIWjUSntb77KoG9pWXc6+R+3SoSL+gLIeg4s/EbJK2HAdKeFR6iHezxCjC1pRsPLZaDcGkOEyS5paV3AsRmPj4ytPLH+m2w2jpcqykV60FhQf5+gefJkDrZ19jBjqtbLe1BMAzvAqmOZkqv+PF0XOZJmu4RU0nMxzRW2xpaWyv4mTztky41gQMMDk2/8MBN7jM3sLZNA0qVZUr9FmVCpKyD4dTpgLVpCTDMKLmo6OKFMnLx45yohdwJm8H7ZAWBaurEjZ8MFwrIlZ38tEXmifgo/p/dPRHGUMcyon8iCEc4F7Sju2prfqf9EhBg+fSnBzOFROwjEywUZMArTQsRuk/Uu/50MSNzhKvAQ3LGX9dc0Oo6FvWEJmmh/n+4ZxyPHmStUR2prMVsdPJFVNc7pPR7AKJ0VlkcKsB1uMUc4K43hDJCPXHIzI40p0aBEfvq0UW0xmqyKOOCWoSABNHuU7cqk4motyzOrth1G0S42LAzDHm4qlos3X+YEzDBw6on8GTGHETAd7N6Ih4Fx3ymG0KbhHWdflOj1CPocY4eR6aPtvomZiVfozd2oepPQCerSGxyH8HVvE=
  - secure: fQJqZlg8nhDPhn2zZX6c+mcSZsulkXFfZI1qo3pzZ2vmcmaqmRSUe8XbseVQKt94CmtilfuNE3P+ZVqpCNZPD0zsa6fu3CE14nhRiess4T3L111APNgP1SXEfxQoY+1/ZT9584R38mBMrS0quCnAYMl9aYwTHwhfTRIvHO05DVmlh1t/u6remLj7U+vayClAc5B3JsLGt5aplQ8FurHP/P6olJc/mUwvE9KFVsna7MUPO0KT0VBUu4cILHX7sjwVsBHchZpRenO5ukPJoOjDwxjLERqQr/m6Io5a60PE1WrO5sjl6IkvKDKii8C1ij3SOzpkW3TKLYbmAip5eyVSy+wZpSZzcZBIXPnezyleRsyngiom/0Mp4xJYU9s0n8133RKEHB3k5aeRWr99Jw7qUamtFZbvY7Qxg2BiEL6qMHkP4ns85vovE5w8pG5GT7j4dPvtfefypiDzquE5phMKFpJ6q5riNVG459bWx6U9CXeb09//O3oKg+x7gWB9aascz8sWFgFU6/3e/20hzNVBiT+AsNFI3W7XrU1GZ38BHyJ6niauHPIThPRSmTtmyg5ZMPX2gCmvALT050la8yyWeNnIzBTAtSIcBS2d7jJP2QYRF0SdlNhhX2zG66z0hC8udos+iiuuXWmCBVc4l2eaY8z4RqaeEV7NEDlmErsGLKY=
  - secure: OVHfTUZbIrM7H4HdB9z5dwwOapjz1HmoytX/sKXanrmLfS4Eoyio+Ib6YQO9lVGsoxvsYG2xUohjDmKpKYhaiy3QEfqeKGJdgDWU6WzZ1OUyPTqL7CPo9wGovWbAbF7mNPBdj3x5qDOp8xvbMqrx33ot2wVkI9tfYenjJ0/MBQSqbyRJGxJ3/9SeK5wSscTX6osNkiwRW4ekr7DpzdHiPYhQ23Ffc6qyep5/kIdqxTXjGD5PAwKAKqtyTD8eToqBCFlT+jNjeMv63fNWc4wIb6Nzwoa+6xTx+Df6plLg9dMSSTY2qgLq8D/Rt1rTRtRwOINIoHeTJPryYPhVSAjdCxBbgqUNkAz2ATxdPBcJwhJM6iBXEOSv+UKOaiEx3gpzFYuTiZ03PHjpNlgiTLLX6qOm0TGMjF7urhpfiLfMc/sutiPw3cIo6jR2nhxlOr7nFRvewDZqw1ykK7n58MC357U58073rIw1breLttrS8/PpVIRR+AYzI7KgDMch0X1nLt5gtU4Q6tOusqlfc/rbm6EEXN9iuahfPqVjW5GFYOMofzqUbutm81hC5dIwnGrEl5FKbNaxrJrQoCHDvpYYxao8Tvc/CFlm1yY9tKk/DheaNTGdkoUROrPeV4yXzFqB6x7f2ixRDo23NTSfpjPE3/4lH8Qr57jZce7bCa7HjUs=
