apiVersion: v2
name: refractr
description: A Helm chart for the refractr redirect application
type: application

# Chart version, bump for any changes
version: 1.0.1

keywords:
  - Mozilla
  - refractr

home: https://github.com/mozilla-it/refractr
sources:
  - https://github.com/mozilla-it/refractr

maintainers:
  - name: Alberto del Barrio
    email: alberto@mozilla.com
