apiVersion: v2
name: refractr
description: A Helm chart for the refractr redirect application
type: application

# Chart version, bump for any changes
version: 1.0.24

keywords:
  - Mozilla
  - refractr
  - redirects

home: https://github.com/mozilla-it/refractr
sources:
  - https://github.com/mozilla-it/refractr

maintainers:
  - name: Alberto del Barrio
    email: alberto@mozilla.com

dependencies:
- name: cert-manager
  version: v0.15.2
  condition: cert-manager.install
  repository: https://charts.jetstack.io
