apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mentoring.fullname" . }}
data:
  DJANGO_ALLOWED_HOSTS: {{ .Values.configMap.allowedHosts }}
  DJANGO_STAFF_GROUPS: {{ .Values.configMap.staffGroups }}
  DJANGO_OIDC_AUTHENTICATION_CALLBACK_URL: {{ .Values.configMap.callbackUrl }}
