---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  {{- if .Values.deployment.annotations }}
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "refractr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "refractr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "refractr.selectorLabels" .  | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "refractr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          envFrom:
          - secretRef:
              name: {{ .Values.deployment.name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.deployment.extraContainers }}
      {{- toYaml .Values.deployment.extraContainers | nindent 8 }}
{{- end }}
{{- if .Values.deployment.extraVolumes }}
      volumes:
      {{- toYaml .Values.deployment.extraVolumes | nindent 6 }}
{{- end }}
