{{- if .Values.my_issuer.create }}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: it-se@mozilla.com
    server: {{ if eq .Values.my_issuer.name "prod" }}{{ .Values.le.prod }}{{ else }}{{ .Values.le.stage }}{{ end }}
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            class: nginx
      - dns01:
          webhook:
            groupName: test
            solverName: webhook
        selector:
          dnsNames:
            - malware-error.mozilla.com

{{- end }}
