{{- if .Values.externalsecret.create }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: refractr
spec:
  backendType: secretsManager
  dataFrom:
    - /{{ .Values.environment }}/refractr
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: refractr
data:
  # echo -n "127.0.0.1:5114" | base64
  PAPERTRAIL_URL: MTI3LjAuMC4xOjUxMTQ=
{{- end }}
