{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.metrics.service.annotations }}
  annotations: {{ toYaml .Values.metrics.service.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "refractr.labels" . | nindent 4 }}
  name: {{ include "refractr.fullname" . }}-metrics
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "refractr.selectorLabels" . | nindent 4 }}
{{- end }}
