---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  labels: {{- include "refractr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 80
    protocol: TCP
  selector:
    {{- include "refractr.selectorLabels" . | nindent 4 }}
