{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fluentd-papertrail.fullname" . }}
  labels:
    {{- include "fluentd-papertrail.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
    - pods
    - namespaces
  verbs:
    - list
    - get
    - watch
{{- end -}}
