{{- if .Values.externalSecrets.enabled }}
{{- $provider := .Values.externalSecrets.provider -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "fluentd-papertrail.secrets" . }}
  labels:
    {{- include "fluentd-papertrail.labels" . | nindent 4 }}
spec:
  {{- if eq $provider "aws" }}
  backendType: secretsManager
  {{- else if eq $provider "gcp" }}
  backendType: gcpSecretsManager
  {{- end }}
  region: {{ .Values.externalSecrets.region }}
  {{- if .Values.externalSecrets.secretsKey }}
  data:
    - key: {{ .Values.externalSecrets.secretsKey }}
      name: FLUENT_PAPERTRAIL_HOST
      property: FLUENT_PAPERTRAIL_HOST
    - key: {{ .Values.externalSecrets.secretsKey }}
      name: FLUENT_PAPERTRAIL_PORT
      property: FLUENT_PAPERTRAIL_PORT
  {{- end }}
{{- end }}
