apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ctms.fullname" . }}
  labels:
    {{- include "ctms.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}-db-migration
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["python", "-m", "alembic", "upgrade", "head"]
        envFrom:
          - secretRef:
              name: {{ include "ctms.fullname" . }}-hook
