apiVersion: v1
kind: Service
metadata:
  name: configmapsecret-controller
  namespace: kube-system
  labels:
    control-plane: configmapsecret-controller
spec:
  selector:
    control-plane: configmapsecret-controller
  ports:
    - name: http-metrics
      port: 9091
      targetPort: http-metrics
