---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: influx-secret
spec:
  backendType: secretsManager
  region: us-west-2
  data:
    - key: "{{ .Values.prom.influx_secret_key }}"
      name: "{{ .Values.prom.influx_secret_name }}"
