{{- if .Values.influxdb.enabled }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: influx-secret
spec:
  backendType: secretsManager
  region: us-west-2
  data:
    - key: "{{ .Values.influxdb.secret_key }}"
      name: "{{ .Values.influxdb.secret_name }}"
      property: "{{ .Values.influxdb.property }}"
{{- end }}
