apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: it-se@mozilla.com
    server: {{ if eq .Values.ingress.le.name "prod" }}{{ .Values.le.prod }}{{ else }}{{ .Values.le.stage }}{{ end }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
