---
apiVersion: v1
kind: Service
metadata:
  name: pastebin
  labels:
    {{- include "pastebin.labels" . | nindent 4 }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.deployment.port }}
  selector:
    {{- include "pastebin.selectorLabels" . | nindent 4 }}
  type: NodePort
