apiVersion: v2
name: mozmoderator
description: A Helm Chart for Mozilla's Moderator application
type: application
version: 0.1.2
appVersion: c285426edacb3a1791bab84f64c16d00e6d865eb
keywords:
  - Mozilla
  - moderator
sources:
  - https://github.com/mozilla/mozmoderator
maintainers:
  - name: Alberto del Barrio
    email: alberto@mozilla.com

dependencies:
- name: mysql
  version: 8.4.2
  condition: mysql.enabled
  repository: https://charts.bitnami.com/bitnami
