configMap:
  annotations: {}
  data:
    VAL: "5"
  labels: {}
  name: pastebin

deployment:
  annotations: {}
  image:
    pullPolicy: Always
    repository: 783633885093.dkr.ecr.us-west-2.amazonaws.com/pastebin
    tag: 3.1.0
  labels: {}
  name: pastebin
  port: 5000
  replicaCount: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

externalSecrets:
  annotations: {}
  enabled: false
  labels: {}
  name: pastebin
  secrets: []
    # - key: /{env}/pastebin/envvar
    #   name: ENV_VAR_NAME
    #   property: envvar_json_key

ingress:
  annotations:
    cert-manager.io/issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "Content-Security-Policy: frame-ancestors 'none'";
  className: "nginx"
  hosts:
    - host: my.domain.name
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: pastebin
          servicePort: http
  image:
    pullPolicy: Always
    repository: 783633885093.dkr.ecr.us-west-2.amazonaws.com/pastebin
    tag: "3.1.0"
  labels: {}
  name: pastebin
  tls:
    - hosts:
        - paste.allizom.com
      secretName: chart-paste-allizom-org

job:
  annotations: {}
  labels: {}
  name: pastebin-manager
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 5

metrics:
  enabled: false

service:
  name: pastebin
  port: 80
  type: NodePort
