{{- if .Values.externalSecret.create -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "mozmoderator.fullname" . }}
spec:
  backendType: secretsManager
  dataFrom:
  - /{{ .Values.environment }}/moderator
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mozmoderator.fullname" . }}
data:
  # echo -n "mysql://moderator:defaultpassword@mysql:3306/moderator" | base64
  DATABASE_URL: bXlzcWw6Ly9tb2RlcmF0b3I6ZGVmYXVsdHBhc3N3b3JkQG15c3FsOjMzMDYvbW9kZXJhdG9y
  MOZILLIANS_API_APPNAME: bW9kZXJhdG9y
  MOZILLIANS_API_KEY: ZmFrZQ==
  OIDC_RP_CLIENT_ID: ZmFrZQ==
  OIDC_RP_CLIENT_SECRET: ZmFrZQ==
  SECRET_KEY: ZmFrZQ==
{{- end }}
